services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: rosatom
      POSTGRES_USER: rosatom
      POSTGRES_PASSWORD: rosatom
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-all-migrations.sql:/docker-entrypoint-initdb.d/init-all-migrations.sql
    ports:
      - "5432:5432"
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rosatom -d rosatom"]
      interval: 5s
      timeout: 3s
      retries: 20
    restart: unless-stopped

  sso:
    build:
      context: ./sso
      dockerfile: Dockerfile
    environment:
      CONFIG_PATH: /app/config/prod.yaml
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "44044:44044"
    networks:
      - app-network
    volumes:
      - ./sso/config/prod.yaml:/app/config/prod.yaml
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "44044"]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 5s

  telephone-book:
    build:
      context: ./telephone_book
      dockerfile: Dockerfile
    environment:
      CONFIG_PATH: /app/config/prod.yaml
    depends_on:
      postgres:
        condition: service_healthy
      sso:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      - app-network
    volumes:
      - ./telephone_book/config/prod.yaml:/app/config/prod.yaml
      - ./telephone_book/frontend:/app/frontend
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "8080"]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 5s

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./telephone_book/frontend:/usr/share/nginx/html
    depends_on:
      telephone-book:
        condition: service_healthy
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "80"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 5s

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge